### ISSUE TITLE
`text-wrap: pretty`

### ISSUE THREAD

**Issue by mrleblanc101** [Stanko/Stanko.github.io#454]
Didn't you used to have Discus comment on your articles ?

I only wanted to add that you should probably use `text-wrap: pretty` instead of `text-wrap: balance` for this kind of usage in [this article](https://muffinman.io/blog/css-fix-to-prevent-orphan-icons/), since balance can create weird looking results depending on your design.

unbalanced:
![Screenshot 2024-11-13 at 2 11 31 PM](https://github.com/user-attachments/assets/f0ca15bf-eac9-43c9-b5c6-16fdc86afe5b)

`text-wrap: balance`:
![Screenshot 2024-11-13 at 2 11 42 PM](https://github.com/user-attachments/assets/8bc8657e-6607-48a2-b357-0c0548d0a2ee)

`text-wrap: pretty`:
![Screenshot 2024-11-13 at 2 11 49 PM](https://github.com/user-attachments/assets/9ca173fe-b5cd-43a4-b62f-8e2a1211cc11)

Also, there is this common hack `some text node<div style="white-space: no-wrap">&nbsp;<svg> ... </svg></div>`

**Comment by Stanko** [comment]
Hey @mrleblanc101,
I considered adding `text-wrap: pretty` in the post, but it is not yet supported in Firefox and Safari, while `balance` has been supported in all browsers since 2023.

But I think you are right, it is definitely worth mentioning it in the post, I'll update it.

Thanks for the feedback!

P. S. I used to have comments on my blog (by using [staticman](https://staticman.net/)) but I removed them at one point.
